services:
  local-ai:
    image: localai/localai:latest-cpu
    container_name: local-ai
    ports:
      - "8080:8080"
    volumes:
      - "./models:/models"
    stdin_open: true
    tty: true
    command: >
      --models-path /models
      --context-size 700
      --threads 4
    restart: always