version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    network_mode: "bridge"

volumes:
  minio-data:
