version: '3'

services:
  redis:
    container_name: redis
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass abc123
    volumes:
      - global-redis-data:/data
    network_mode: "bridge"

volumes:
  global-redis-data:
