version: '3'

services:
  postgresql:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - global-pg-data:/var/lib/postgresql/data
    network_mode: "bridge"

volumes:
  global-pg-data:
