
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - global-mysql-data:/var/lib/mysql

volumes:
  global-mysql-data:
