
version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.10
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
    volumes:
      - global-mariadb-data:/var/lib/mysql
    network_mode: "bridge"

volumes:
  global-mariadb-data:
